import Link from "next/link";
import { ReservationForm } from "@/components/ReservationForm";
import { faqs, services, site } from "@/content/site";

const wa = `https://wa.me/${site.whatsappDigits}?text=${encodeURIComponent("Hola Vita Lima, deseo información para reservar una experiencia.")}`;

export default function Home() {
  return (
    <main>
      <header className="header"><a className="brand" href="#inicio"><span className="brand-mark">VL</span><span><b>Vita Lima</b><small>SPA & BIENESTAR</small></span></a><nav><a href="#servicios">Servicios</a><a href="#experiencias">Experiencias</a><a href="#sedes">Sedes</a><a href="#faq">Preguntas</a></nav><a className="button small" href={wa} target="_blank" rel="noreferrer">Reservar</a></header>

      <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">Masajes en Lima · San Borja · Miraflores</p><h1>Regálate una pausa.<br/><em>Tu cuerpo la necesita.</em></h1><p className="lead">Experiencias de bienestar personalizadas para liberar tensión, recuperar calma y volver a sentirte bien.</p><div className="actions"><a className="button primary" href={wa} target="_blank" rel="noreferrer">Reservar por WhatsApp</a><a className="text-link" href="#servicios">Ver servicios <span>↓</span></a></div><div className="trust"><span>13+ años de experiencia</span><span>Atención personalizada</span><span>Dos sedes en Lima</span></div></div><div className="hero-art"><div className="sun"></div><div className="arch"><div className="leaf leaf-one"></div><div className="leaf leaf-two"></div><div className="stone stone-one"></div><div className="stone stone-two"></div><p>Respira<br/>Suelta<br/>Renueva</p></div><div className="floating-card"><small>Tu momento</small><strong>empieza aquí</strong></div></div></section>

      <section className="intro section"><p className="eyebrow">Bienestar hecho a tu medida</p><h2>No todos los días pesan igual.<br/>Tu masaje tampoco debería ser igual.</h2><p>Escuchamos cómo llegas, adaptamos la intensidad y te ayudamos a elegir la experiencia que mejor acompaña lo que necesitas hoy.</p></section>

      <section className="section services" id="servicios"><div className="section-heading"><div><p className="eyebrow">Servicios principales</p><h2>Elige cómo quieres sentirte</h2></div><p>Opciones claras, tiempos definidos y atención profesional. Los precios corresponden a una persona.</p></div><div className="service-grid">{services.map((service, index) => <article className="service-card" key={service.name}><span className="service-number">0{index + 1}</span><div><p className="service-meta">{service.duration} · {service.price}</p><h3>{service.name}</h3><p>{service.copy}</p></div><a href={`${wa}&text=${encodeURIComponent(`Hola Vita Lima, deseo reservar ${service.name}.`)}`} target="_blank" rel="noreferrer" aria-label={`Reservar ${service.name}`}>Reservar <span>↗</span></a></article>)}</div></section>

      <section className="section experiences" id="experiencias"><div className="section-heading light"><div><p className="eyebrow">Más formas de cuidarte</p><h2>Experiencias que se comparten, se regalan y se recuerdan</h2></div></div><div className="experience-grid"><article className="experience featured"><span>Para dos</span><h3>Una pausa en pareja</h3><p>Compartan una experiencia de bienestar y salgan del ruido por un momento.</p><a href={wa} target="_blank" rel="noreferrer">Consultar disponibilidad ↗</a></article><article className="experience gift"><span>Gift Cards</span><h3>Regala bienestar</h3><p>Un detalle flexible, personal y perfecto para celebrar o agradecer.</p><a href={wa} target="_blank" rel="noreferrer">Quiero regalar ↗</a></article><article className="experience home"><span>A domicilio</span><h3>Nosotros llevamos la calma</h3><p>Camilla, implementos y atención profesional en la comodidad de tu espacio.</p><a href={wa} target="_blank" rel="noreferrer">Consultar cobertura ↗</a></article><article className="experience corporate"><span>Empresas</span><h3>Bienestar para tu equipo</h3><p>Activaciones, masajes y experiencias pensadas para colaboradores.</p><a href={`mailto:${site.email}?subject=Propuesta corporativa Vita Lima`}>Solicitar propuesta ↗</a></article></div></section>

      <section className="section locations" id="sedes"><div className="location-copy"><p className="eyebrow">Nuestras sedes</p><h2>Encuentra tu pausa en Lima</h2><p>Confirma tu cita antes de acercarte. Te ayudaremos a elegir la sede y el horario más conveniente.</p><a className="button primary" href={wa} target="_blank" rel="noreferrer">Coordinar una visita</a></div><div className="location-list"><article><span>01</span><div><p>San Borja</p><h3>Av. Aviación 3358, oficina 204</h3><small>Lunes a sábado · principalmente de 3:00 p. m. a 8:00 p. m.</small></div></article><article><span>02</span><div><p>Miraflores</p><h3>Av. Larco 812, oficina 306</h3><small>Atención previa reserva</small></div></article></div></section>

      <section className="section quote"><blockquote>“Más que una sesión, buscamos que salgas sintiendo que volviste a ti.”</blockquote><p>Vita Lima Spa · bienestar cercano, profesional y humano.</p></section>

      <section className="section booking" id="reservar"><div className="booking-copy"><p className="eyebrow">Reserva tu experiencia</p><h2>Cuéntanos cuándo quieres venir</h2><p>Envíanos tus datos y nuestro equipo te contactará para confirmar disponibilidad, adelanto y detalles de tu atención.</p><div className="contact-note"><span>WhatsApp</span><strong>{site.whatsappDisplay}</strong><span>Correo</span><strong>{site.email}</strong></div></div><ReservationForm /></section>

      <section className="section faq" id="faq"><div><p className="eyebrow">Preguntas frecuentes</p><h2>Todo claro antes de reservar</h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>

      <footer><div className="footer-brand"><div className="brand-mark">VL</div><h2>Vita Lima</h2><p>Un espacio para bajar el ritmo, liberar tensión y reconectar contigo.</p></div><div><h3>Explora</h3><a href="#servicios">Servicios</a><a href="#experiencias">Experiencias</a><a href="#sedes">Sedes</a><a href="#reservar">Reservar</a></div><div><h3>Contacto</h3><a href={wa}>WhatsApp</a><a href={`mailto:${site.email}`}>{site.email}</a><a href={site.instagram}>Instagram</a><a href={site.facebook}>Facebook</a></div><div><h3>Legal</h3><Link href="/politica-de-privacidad">Privacidad</Link><Link href="/terminos-y-condiciones">Términos</Link></div><p className="copyright">© {new Date().getFullYear()} Vita Lima Spa. Todos los derechos reservados.</p></footer>
      <a className="whatsapp" href={wa} target="_blank" rel="noreferrer" aria-label="Reservar por WhatsApp">WA</a>
    </main>
  );
}
