services:
  vita-lima-web:
    container_name: vita-lima-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_SITE_URL: https://nueva.vitalimaspa.com
      NEXT_PUBLIC_WHATSAPP: "51907308415"
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - default
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
    name: n8n_default
