export const serviceImageRotations: Record<string, string[]> = {
  "relax-vital": [
    "/images/relax-vital/relax-01-shoulders.webp",
    "/images/relax-vital/relax-02-pressure.webp",
    "/images/relax-vital/relax-03-palms.webp",
    "/images/relax-vital/relax-04-reflexology.webp",
  ],
  "alivio-integral": [
    "/images/alivio-integral/alivio-01-hombros.webp",
    "/images/alivio-integral/alivio-02-cuello.webp",
    "/images/alivio-integral/alivio-03-reflexologia.webp",
    "/images/alivio-integral/alivio-04-lumbar.webp",
  ],
  "balance-plus": [
    "/images/balance-plus/balance-01-piedras-calientes.webp",
    "/images/balance-plus/balance-02-reflexologia.webp",
    "/images/balance-plus/balance-03-exfoliacion-espalda.webp",
    "/images/balance-plus/balance-04-masaje.webp",
  ],
  relax: [
    "/images/relax/relax-01-piedras-aromaterapia.webp",
    "/images/relax/relax-02-reflexologia-podal.webp",
    "/images/relax/relax-03-vino-o-infusion.webp",
    "/images/relax/relax-04-masaje.webp",
  ],
  deluxe: [
    "/images/deluxe/deluxe-01-piedras-aromaterapia.webp",
    "/images/deluxe/deluxe-02-facial-colageno.webp",
    "/images/deluxe/deluxe-03-reflexologia-podal.webp",
    "/images/deluxe/deluxe-04-vino-o-infusion.webp",
  ],
  supreme: [
    "/images/supreme/supreme-01-piedras-aromaterapia.webp",
    "/images/supreme/supreme-02-exfoliacion-hidratacion.webp",
    "/images/supreme/supreme-03-facial-hialuronico.webp",
    "/images/supreme/supreme-04-reflexologia-podal.webp",
    "/images/supreme/supreme-05-descanso-pareja.webp",
  ],
  "lifting-tinturado-planchado-cejas": [
    "/images/lifting-pestanas-cejas/lifting-01-pestanas.webp",
    "/images/lifting-pestanas-cejas/lifting-02-planchado-cejas.webp",
    "/images/lifting-pestanas-cejas/lifting-03-tinturado.webp",
    "/images/lifting-pestanas-cejas/lifting-04-resultado.webp",
  ],
  "terapia-vita": [
    "/images/terapia-vita/terapia-vita-01-tens-aplicacion.webp",
    "/images/terapia-vita/terapia-vita-02-tens-control.webp",
    "/images/terapia-vita/terapia-vita-03-ventosas-colocacion.webp",
    "/images/terapia-vita/terapia-vita-04-ventosas-ajuste.webp",
  ],
  "deep-balance-120": [
    "/images/deep-balance-120/deep-balance-120-01-piedras-calientes.webp",
    "/images/deep-balance-120/deep-balance-120-02-compresas-calientes.webp",
    "/images/deep-balance-120/deep-balance-120-03-reflexologia-podal.webp",
    "/images/deep-balance-120/deep-balance-120-04-masaje-hombros.webp",
  ],
  "aroma-zen": [
    "/images/aroma-zen/aroma-zen-01-masaje-hombros.webp",
    "/images/aroma-zen/aroma-zen-02-reflexologia-podal.webp",
    "/images/aroma-zen/aroma-zen-03-aromaterapia.webp",
    "/images/aroma-zen/aroma-zen-04-cuello-infusion.webp",
  ],
  "coco-premium": [
    "/images/coco-premium/coco-premium-01-piedras-calientes.webp",
    "/images/coco-premium/coco-premium-02-exfoliacion-coco.webp",
    "/images/coco-premium/coco-premium-03-reflexologia-podal.webp",
    "/images/coco-premium/coco-premium-04-vino-o-infusion.webp",
  ],
  "piedras-calientes": [
    "/images/piedras-calientes/piedras-calientes-01-aplicacion.webp",
    "/images/piedras-calientes/piedras-calientes-02-hombros.webp",
    "/images/piedras-calientes/piedras-calientes-03-preparacion.webp",
    "/images/piedras-calientes/piedras-calientes-04-manos.webp",
  ],
  "drenaje-linfatico": [
    "/images/drenaje-linfatico/drenaje-linfatico-01-brazo.webp",
    "/images/drenaje-linfatico/drenaje-linfatico-02-pierna.webp",
    "/images/drenaje-linfatico/drenaje-linfatico-03-hombros.webp",
    "/images/drenaje-linfatico/drenaje-linfatico-04-preparacion.webp",
  ],
  ventosas: [
    "/images/ventosas/ventosas-01-aplicacion-espalda.webp",
    "/images/ventosas/ventosas-02-cuello.webp",
    "/images/ventosas/ventosas-03-brazo.webp",
    "/images/ventosas/ventosas-04-preparacion.webp",
  ],
  "glow-facial-plus": [
    "/images/glow-facial-plus/glow-facial-plus-01-limpieza.webp",
    "/images/glow-facial-plus/glow-facial-plus-02-mascarilla.webp",
    "/images/glow-facial-plus/glow-facial-plus-03-piedras-hombros.webp",
    "/images/glow-facial-plus/glow-facial-plus-04-infusion.webp",
  ],
  "para-regalar-60": [
    "/images/para-regalar-60/para-regalar-01-masaje.webp",
    "/images/para-regalar-60/para-regalar-02-piedras-calientes.webp",
    "/images/para-regalar-60/para-regalar-03-reflexologia-podal.webp",
    "/images/para-regalar-60/para-regalar-04-regalo-bebida.webp",
  ],
  "limpieza-facial-express": [
    "/images/limpieza-facial-express/facial-express-01-limpieza.webp",
    "/images/limpieza-facial-express/facial-express-02-preparacion.webp",
    "/images/limpieza-facial-express/facial-express-03-gel.webp",
    "/images/limpieza-facial-express/facial-express-04-retiro.webp",
  ],
  "facial-mascarilla-barro": [
    "/images/facial-mascarilla-barro/barro-01-aplicacion.webp",
    "/images/facial-mascarilla-barro/barro-02-tratamiento.webp",
    "/images/facial-mascarilla-barro/barro-03-preparacion.webp",
    "/images/facial-mascarilla-barro/barro-04-retiro.webp",
  ],
  "lifting-de-pestanas": [
    "/images/lifting-de-pestanas/lifting-01-proteccion.webp",
    "/images/lifting-de-pestanas/lifting-02-tinturado.webp",
    "/images/lifting-de-pestanas/lifting-03-resultado.webp",
    "/images/lifting-de-pestanas/lifting-04-procedimiento.webp",
  ],
  "planchado-de-cejas": [
    "/images/planchado-de-cejas/cejas-01-peinado.webp",
    "/images/planchado-de-cejas/cejas-02-alineacion.webp",
    "/images/planchado-de-cejas/cejas-03-resultado.webp",
    "/images/planchado-de-cejas/cejas-04-detalle.webp",
  ],
};
