export type ServiceCategory = "individual" | "couples" | "home" | "program" | "beauty" | "facial";

export type Service = {
  code: string;
  slug: string;
  category: ServiceCategory;
  name: string;
  // Nombre en inglés. Opcional: si no está definido, la versión en inglés
  // del sitio muestra el nombre en español como respaldo.
  nameEn?: string;
  duration: number;
  price: number;
  // Precio de lista antes del descuento vigente. Opcional: solo se define
  // cuando se confirmó el precio "antes" real; si no está presente, la
  // tarjeta muestra únicamente el precio final, sin comparación.
  originalPrice?: number;
  includes: string;
  // Versión en inglés de "includes". Opcional, mismo respaldo que nameEn.
  includesEn?: string;
  venue: string;
  mode: "IN_BRANCH" | "HOME";
  group: "PROMOS_1P" | "PACK_2P" | "HOME" | "SESSIONS" | "BEAUTY" | "FACIAL";
  featured: boolean;
  badge: string;
  // Versión en inglés de "badge". Opcional, mismo respaldo que nameEn.
  badgeEn?: string;
  featuredSummary?: string;
  // Versión en inglés de "featuredSummary". Opcional, mismo respaldo que nameEn.
  featuredSummaryEn?: string;
};

export const services: Service[] = [
  {
    code: "SVC_016",
    slug: "relax-vital",
    category: "individual",
    name: "🌿 Relax Vital",
    nameEn: "🌿 Relax Vital",
    duration: 60,
    price: 70,
    originalPrice: 80,
    includes: "Masaje Relajante + Reflexología",
    includesEn: "Relaxing Massage + Reflexology",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: true,
    badge: "Más elegido",
    badgeEn: "Most Popular",
    featuredSummary: "Masaje Relajante + Reflexología",
    featuredSummaryEn: "Relaxing Massage + Reflexology",
  },
  {
    code: "SVC_012",
    slug: "espalda-libre",
    category: "individual",
    name: "🌤️ Espalda Libre",
    nameEn: "🌤️ Back Relief",
    duration: 45,
    price: 58,
    originalPrice: 68,
    includes: "Masaje Relajante o Descontracturante de Parte Superior",
    includesEn: "Relaxing or Deep-Tissue Upper Back Massage",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_013",
    slug: "alivio-integral",
    category: "individual",
    name: "💆‍♂️ Alivio Integral",
    nameEn: "💆‍♂️ Full Relief",
    duration: 60,
    price: 80,
    originalPrice: 88,
    includes: "Masaje Descontracturante + Reflexología",
    includesEn: "Deep-Tissue Massage + Reflexology",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: true,
    badge: "Ideal para tensiones",
    badgeEn: "Great for Tension",
    featuredSummary: "Masaje Descontracturante + Reflexología",
    featuredSummaryEn: "Deep-Tissue Massage + Reflexology",
  },
  {
    code: "SVC_019",
    slug: "terapia-vita",
    category: "individual",
    name: "👐 Terapia Vita",
    nameEn: "👐 Vita Therapy",
    duration: 60,
    price: 80,
    originalPrice: 90,
    includes: "Masaje Terapéutico ideal para aliviar tensiones musculares",
    includesEn: "Therapeutic massage, ideal for relieving muscle tension",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_017",
    slug: "balance-plus",
    category: "individual",
    name: "🌿 Balance Plus",
    nameEn: "🌿 Balance Plus",
    duration: 70,
    price: 88,
    originalPrice: 95,
    includes: "Masaje Relajante o Descontracturante + Piedras Calientes + Reflexología + Exfoliación de Espalda",
    includesEn: "Relaxing or Deep-Tissue Massage + Hot Stones + Reflexology + Back Exfoliation",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: true,
    badge: "Experiencia completa",
    badgeEn: "Complete Experience",
    featuredSummary: "Masaje Relajante o Descontracturante + Piedras Calientes + Reflexología + Exfoliación de Espalda",
    featuredSummaryEn: "Relaxing or Deep-Tissue Massage + Hot Stones + Reflexology + Back Exfoliation",
  },
  {
    code: "SVC_007",
    slug: "glow-facial",
    category: "individual",
    name: "✨ Glow Facial",
    nameEn: "✨ Glow Facial",
    duration: 75,
    price: 99,
    originalPrice: 108,
    includes: "Masaje Relajante o Descontracturante + Limpieza Facial Express con Mascarilla de Colágeno",
    includesEn: "Relaxing or Deep-Tissue Massage + Express Facial Cleanse with Collagen Mask",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_018",
    slug: "deep-balance-120",
    category: "individual",
    name: "🌙 Deep Balance 120",
    nameEn: "🌙 Deep Balance 120",
    duration: 120,
    price: 148,
    originalPrice: 158,
    includes: "Masaje Relajante y Descontracturante + Piedras Calientes + Reflexología + Compresas Calientes",
    includesEn: "Relaxing and Deep-Tissue Massage + Hot Stones + Reflexology + Hot Compresses",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_011",
    slug: "aroma-zen",
    category: "individual",
    name: "🕯️ Aroma Zen",
    nameEn: "🕯️ Aroma Zen",
    duration: 60,
    price: 89,
    originalPrice: 99,
    includes: "Masaje Relajante o Descontracturante + Reflexología + Aromaterapia. Incluye nuestra Vela Indalo de Soja para tu sesión y te la llevas de regalo",
    includesEn: "Relaxing or Deep-Tissue Massage + Reflexology + Aromatherapy. Includes our Indalo Soy Candle for your session, yours to keep as a gift",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_020",
    slug: "coco-premium",
    category: "individual",
    name: "🥥 Coco Premium",
    nameEn: "🥥 Coco Premium",
    duration: 80,
    price: 100,
    originalPrice: 110,
    includes: "Masaje Relajante o Descontracturante + Piedras Calientes + Exfoliación de Coco + Reflexología + Aromaterapia + 1 Copa de Vino o Infusión",
    includesEn: "Relaxing or Deep-Tissue Massage + Hot Stones + Coconut Exfoliation + Reflexology + Aromatherapy + 1 Glass of Wine or Herbal Tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_030",
    slug: "piedras-calientes",
    category: "individual",
    name: "🔥 Piedras Calientes",
    nameEn: "🔥 Hot Stones",
    duration: 60,
    price: 75,
    includes: "Masaje relajante con piedras calientes",
    includesEn: "Relaxing massage with hot stones",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_031",
    slug: "bambuterapia",
    category: "individual",
    name: "🎋 Bambuterapia",
    nameEn: "🎋 Bamboo Therapy",
    duration: 60,
    price: 75,
    includes: "Masaje relajante con bambuterapia",
    includesEn: "Relaxing massage with bamboo therapy",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_032",
    slug: "shiatsu",
    category: "individual",
    name: "🙌 Shiatsu",
    nameEn: "🙌 Shiatsu",
    duration: 60,
    price: 80,
    includes: "Masaje shiatsu de presión con dedos y palmas para liberar tensión",
    includesEn: "Shiatsu pressure massage with fingers and palms to release tension",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_033",
    slug: "drenaje-linfatico",
    category: "individual",
    name: "💧 Drenaje Linfático",
    nameEn: "💧 Lymphatic Drainage",
    duration: 60,
    price: 70,
    includes: "Masaje de drenaje linfático para reducir retención de líquidos",
    includesEn: "Lymphatic drainage massage to reduce fluid retention",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_034",
    slug: "masaje-prenatal",
    category: "individual",
    name: "🤰 Masaje Prenatal",
    nameEn: "🤰 Prenatal Massage",
    duration: 60,
    price: 70,
    includes: "Masaje suave y seguro para gestantes. 2 sesiones por S/ 128",
    includesEn: "Gentle, safe massage for expecting mothers. 2 sessions for S/ 128",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_035",
    slug: "bioenergetico-esferas-solo",
    category: "individual",
    name: "🧿 Bioenergético con Esferas Chinas",
    nameEn: "🧿 Bioenergetic Chinese Sphere Massage",
    duration: 70,
    price: 88,
    includes: "Masaje bioenergético con esferas chinas",
    includesEn: "Bioenergetic massage with Chinese spheres",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_036",
    slug: "ventosas",
    category: "individual",
    name: "🫙 Ventosas + Masaje",
    nameEn: "🫙 Cupping + Massage",
    duration: 60,
    price: 80,
    includes: "Masaje relajante o descontracturante con ventosas",
    includesEn: "Relaxing or deep-tissue massage with cupping",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_037",
    slug: "reflexologia",
    category: "individual",
    name: "🦶 Reflexología",
    nameEn: "🦶 Reflexology",
    duration: 30,
    price: 40,
    includes: "Reflexología podal",
    includesEn: "Foot reflexology",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_038",
    slug: "reflexologia-plus",
    category: "individual",
    name: "🦶 Reflexología Plus",
    nameEn: "🦶 Reflexology Plus",
    duration: 45,
    price: 50,
    includes: "Reflexología podal extendida",
    includesEn: "Extended foot reflexology",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_039",
    slug: "para-regalar-60",
    category: "individual",
    name: "🎁 Para Regalar",
    nameEn: "🎁 Gift Treat",
    duration: 60,
    price: 98,
    includes: "Masaje relajante + piedras calientes + reflexología + oso de peluche + bebida",
    includesEn: "Relaxing massage + hot stones + reflexology + teddy bear + drink",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_040",
    slug: "para-regalar-80",
    category: "individual",
    name: "🎁 Para Regalar Plus",
    nameEn: "🎁 Gift Treat Plus",
    duration: 80,
    price: 118,
    includes: "Masaje relajante + piedras calientes + reflexología + exfoliación de espalda + oso de peluche + bebida",
    includesEn: "Relaxing massage + hot stones + reflexology + back exfoliation + teddy bear + drink",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_041",
    slug: "bioenergetico-oriental",
    category: "individual",
    name: "🌸 Bioenergético Oriental",
    nameEn: "🌸 Oriental Bioenergetic",
    duration: 70,
    price: 88,
    includes: "Esferas chinas + bambuterapia + reflexología + armonización con cuencos",
    includesEn: "Chinese spheres + bamboo therapy + reflexology + singing bowl harmonization",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_042",
    slug: "glow-facial-plus",
    category: "individual",
    name: "✨ Glow Facial Plus",
    nameEn: "✨ Glow Facial Plus",
    duration: 80,
    price: 120,
    includes: "Masaje + piedras calientes + limpieza facial + bebida",
    includesEn: "Massage + hot stones + facial cleanse + drink",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_043",
    slug: "glow-facial-premium",
    category: "individual",
    name: "✨ Glow Facial Premium",
    nameEn: "✨ Glow Facial Premium",
    duration: 90,
    price: 155,
    includes: "Masaje + piedras calientes + mascarilla lifting de ácido hialurónico + serum antioxidante + bebida",
    includesEn: "Massage + hot stones + hyaluronic acid lifting mask + antioxidant serum + drink",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_002",
    slug: "break-time",
    category: "couples",
    name: "⏳ Break Time",
    nameEn: "⏳ Break Time",
    duration: 50,
    price: 118,
    originalPrice: 125,
    includes: "Masaje relajante o descontracturante",
    includesEn: "Relaxing or deep-tissue massage",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_014",
    slug: "sacro-craneal",
    category: "couples",
    name: "🧠 Sacro Craneal",
    nameEn: "🧠 Cranio-Sacral",
    duration: 60,
    price: 138,
    originalPrice: 146,
    includes: "Masaje sacro-craneal + compresa herbal + masaje relajante + reflexología podal + aromaterapia",
    includesEn: "Cranio-sacral massage + herbal compress + relaxing massage + foot reflexology + aromatherapy",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_003",
    slug: "respira",
    category: "couples",
    name: "🌬️ Respira",
    nameEn: "🌬️ Respira",
    duration: 60,
    price: 149,
    originalPrice: 159,
    includes: "Masaje relajante + bambuterapia + hidratación corporal + reflexología podal + copa de vino o infusión",
    includesEn: "Relaxing massage + bamboo therapy + body hydration + foot reflexology + glass of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_010",
    slug: "relax",
    category: "couples",
    name: "✨ Relax",
    nameEn: "✨ Relax",
    duration: 60,
    price: 149,
    originalPrice: 160,
    includes: "Masaje relajante y/o descontracturante + piedras calientes + reflexología podal + aromaterapia + copa de vino o infusión",
    includesEn: "Relaxing and/or deep-tissue massage + hot stones + foot reflexology + aromatherapy + glass of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: true,
    badge: "Para dos",
    badgeEn: "For Two",
    featuredSummary: "Masaje relajante y/o descontracturante + piedras calientes + reflexología podal",
    featuredSummaryEn: "Relaxing and/or deep-tissue massage + hot stones + foot reflexology",
  },
  {
    code: "SVC_004",
    slug: "vita",
    category: "couples",
    name: "🌄 Vita",
    nameEn: "🌄 Vita",
    duration: 70,
    price: 159,
    originalPrice: 169,
    includes: "Masaje relajante + piedras calientes + reflexología podal + aromaterapia + exfoliación posterior (chocolate o durazno) + copa de vino o infusión",
    includesEn: "Relaxing massage + hot stones + foot reflexology + aromatherapy + back exfoliation (chocolate or peach) + glass of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_005",
    slug: "renova",
    category: "couples",
    name: "🌶️ Renova",
    nameEn: "🌶️ Renova",
    duration: 70,
    price: 159,
    originalPrice: 169,
    includes: "Masaje relajante herbal + bambuterapia + reflexología podal + aromaterapia + masaje bioenergético con esferas chinas + copa de vino o infusión",
    includesEn: "Relaxing herbal massage + bamboo therapy + foot reflexology + aromatherapy + bioenergetic massage with Chinese spheres + glass of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_006",
    slug: "renace",
    category: "couples",
    name: "🍃 Renace",
    nameEn: "🍃 Renace",
    duration: 65,
    price: 169,
    originalPrice: 189,
    includes: "Masaje descontracturante/relajante + sesión TENS + exfoliación de espalda + bioenergético con esferas chinas + reflexología podal + aromaterapia + 2 copas de vino o infusión",
    includesEn: "Deep-tissue/relaxing massage + TENS session + back exfoliation + bioenergetic Chinese sphere massage + foot reflexology + aromatherapy + 2 glasses of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_021",
    slug: "esencia",
    category: "couples",
    name: "🕯️ Esencia",
    nameEn: "🕯️ Esencia",
    duration: 70,
    price: 178,
    originalPrice: 189,
    includes: "Masaje relajante + piedras calientes + reflexología podal + aromaterapia con vela de soja artesanal + copa de vino o infusión",
    includesEn: "Relaxing massage + hot stones + foot reflexology + aromatherapy with artisanal soy candle + glass of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_001",
    slug: "deluxe",
    category: "couples",
    name: "🌟 Deluxe",
    nameEn: "🌟 Deluxe",
    duration: 90,
    price: 229,
    originalPrice: 250,
    includes: "Masaje relajante + descontracturante + piedras calientes + reflexología podal + aromaterapia + limpieza facial express con mascarilla de colágeno + copa de vino o infusión",
    includesEn: "Relaxing + deep-tissue massage + hot stones + foot reflexology + aromatherapy + express facial cleanse with collagen mask + glass of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: true,
    badge: "Premium",
    badgeEn: "Premium",
    featuredSummary: "Masaje relajante + descontracturante + piedras calientes + reflexología podal",
    featuredSummaryEn: "Relaxing + deep-tissue massage + hot stones + foot reflexology",
  },
  {
    code: "SVC_022",
    slug: "royale",
    category: "couples",
    name: "👑 Royale",
    nameEn: "👑 Royale",
    duration: 120,
    price: 279,
    originalPrice: 300,
    includes: "Masaje relajante/descontracturante (full body) + piedras calientes + exfoliación de espalda + mascarilla de ácido hialurónico + reflexología podal + hidratación de manos + aromaterapia",
    includesEn: "Relaxing/deep-tissue full-body massage + hot stones + back exfoliation + hyaluronic acid mask + foot reflexology + hand hydration + aromatherapy",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_015",
    slug: "supreme",
    category: "couples",
    name: "🌅 Supreme",
    nameEn: "🌅 Supreme",
    duration: 150,
    price: 329,
    originalPrice: 359,
    includes: "Masaje relajante/descontracturante (full body) + piedras calientes + exfoliación de espalda + mascarilla de ácido hialurónico + reflexología podal + hidratación corporal + aromaterapia con vela de soja artesanal + descanso en sala de pareja + copa de vino o infusión",
    includesEn: "Relaxing/deep-tissue full-body massage + hot stones + back exfoliation + hyaluronic acid mask + foot reflexology + body hydration + aromatherapy with artisanal soy candle + rest in couples' lounge + glass of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: true,
    badge: "Signature",
    badgeEn: "Signature",
    featuredSummary: "Masaje relajante/descontracturante (full body) + piedras calientes + exfoliación de espalda",
    featuredSummaryEn: "Relaxing/deep-tissue full-body massage + hot stones + back exfoliation",
  },
  {
    code: "SVC_048",
    slug: "facial-express-2p",
    category: "couples",
    name: "💑 Facial Express en Pareja",
    nameEn: "💑 Couples Express Facial",
    duration: 70,
    price: 219,
    includes: "Masaje + piedras calientes + limpieza facial express con mascarilla de colágeno + reflexología + aromaterapia + 2 copas de vino o infusión",
    includesEn: "Massage + hot stones + express facial cleanse with collagen mask + reflexology + aromatherapy + 2 glasses of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_049",
    slug: "facial-full-body-2p",
    category: "couples",
    name: "💑 Facial Full Body en Pareja",
    nameEn: "💑 Couples Full-Body Facial",
    duration: 90,
    price: 269,
    includes: "Masaje completo + piedras calientes + exfoliación de espalda + mascarilla de ácido hialurónico + reflexología + hidratación de manos + aromaterapia + 2 copas de vino o infusión",
    includesEn: "Full-body massage + hot stones + back exfoliation + hyaluronic acid mask + reflexology + hand hydration + aromatherapy + 2 glasses of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_050",
    slug: "coco-premium-2p",
    category: "couples",
    name: "🥥 Coco Premium en Pareja",
    nameEn: "🥥 Coco Premium for Couples",
    duration: 80,
    price: 210,
    includes: "Masaje relajante y/o descontracturante + piedras calientes + exfoliación de coco + reflexología podal + aromaterapia + 2 copas de vino o infusión",
    includesEn: "Relaxing and/or deep-tissue massage + hot stones + coconut exfoliation + foot reflexology + aromatherapy + 2 glasses of wine or herbal tea",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_009",
    slug: "masaje-domicilio-1-hora",
    category: "home",
    name: "Masaje a domicilio (1 hora)",
    nameEn: "At-Home Massage (1 hour)",
    duration: 60,
    price: 120,
    includes: "Servicio a domicilio con camilla. Servicios disponibles: masaje relajante, descontracturante, deportivo, terapéutico, holístico o reflexología podal. Traslado incluido a Miraflores. Recargo de S/30 para San Borja, Surco, San Isidro y Barranco. Reserva con mínimo 24 horas de anticipación.",
    includesEn: "At-home service with massage table. Available treatments: relaxing, deep-tissue, sports, therapeutic, holistic massage, or foot reflexology. Travel included to Miraflores. S/30 surcharge for San Borja, Surco, San Isidro, and Barranco. Book at least 24 hours in advance.",
    venue: "Lima",
    mode: "HOME",
    group: "HOME",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_008",
    slug: "masaje-domicilio-2-horas",
    category: "home",
    name: "Masaje a domicilio (2 horas)",
    nameEn: "At-Home Massage (2 hours)",
    duration: 120,
    price: 230,
    includes: "Servicio a domicilio con camilla. Servicios disponibles: masaje relajante, descontracturante, deportivo, terapéutico, holístico o reflexología podal. Traslado incluido a Miraflores. Recargo de S/30 para San Borja, Surco, San Isidro y Barranco. Reserva con mínimo 24 horas de anticipación.",
    includesEn: "At-home service with massage table. Available treatments: relaxing, deep-tissue, sports, therapeutic, holistic massage, or foot reflexology. Travel included to Miraflores. S/30 surcharge for San Borja, Surco, San Isidro, and Barranco. Book at least 24 hours in advance.",
    venue: "Lima",
    mode: "HOME",
    group: "HOME",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_024",
    slug: "programa-relajante-5-sesiones",
    category: "program",
    name: "Programa Relajante – 5 sesiones",
    nameEn: "Relaxation Program – 5 Sessions",
    duration: 60,
    price: 248,
    includes: "5 sesiones de masaje relajante",
    includesEn: "5 relaxing massage sessions",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_025",
    slug: "programa-relajante-10-sesiones",
    category: "program",
    name: "Programa Relajante – 10 sesiones",
    nameEn: "Relaxation Program – 10 Sessions",
    duration: 60,
    price: 408,
    includes: "10 sesiones de masaje relajante",
    includesEn: "10 relaxing massage sessions",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_026",
    slug: "programa-terapia-muscular-5-sesiones",
    category: "program",
    name: "Programa Terapia Muscular – 5 sesiones",
    nameEn: "Muscle Therapy Program – 5 Sessions",
    duration: 60,
    price: 325,
    includes: "5 sesiones: descontracturante, terapéutico, piedras calientes o bambuterapia",
    includesEn: "5 sessions: deep-tissue, therapeutic, hot stones, or bamboo therapy",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_023",
    slug: "programa-terapia-muscular-10-sesiones",
    category: "program",
    name: "Programa Terapia Muscular – 10 sesiones",
    nameEn: "Muscle Therapy Program – 10 Sessions",
    duration: 60,
    price: 640,
    includes: "10 sesiones: descontracturante, terapéutico, piedras calientes o bambuterapia",
    includesEn: "10 sessions: deep-tissue, therapeutic, hot stones, or bamboo therapy",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_027",
    slug: "lifting-de-pestanas",
    category: "beauty",
    name: "Lifting de Pestañas",
    nameEn: "Lash Lift",
    duration: 60,
    price: 90,
    includes: "Eleva y realza las pestañas naturales desde la raíz. Incluye tinturado con henna.",
    includesEn: "Lifts and enhances natural lashes from the root. Includes henna tinting.",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "BEAUTY",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_028",
    slug: "planchado-de-cejas",
    category: "beauty",
    name: "Planchado de Cejas",
    nameEn: "Brow Lamination",
    duration: 25,
    price: 50,
    includes: "Alinea y define las cejas, ayudando a controlar el vello rebelde y resaltar su forma natural.",
    includesEn: "Aligns and defines brows, taming stray hairs and enhancing their natural shape.",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "BEAUTY",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_029",
    slug: "lifting-tinturado-planchado-cejas",
    category: "beauty",
    name: "Lifting de Pestañas + Tinturado + Planchado de Cejas",
    nameEn: "Lash Lift + Tint + Brow Lamination",
    duration: 90,
    price: 130,
    includes: "Tratamiento integral para realzar pestañas y cejas con lifting, tinturado y planchado.",
    includesEn: "Complete treatment to enhance lashes and brows with lifting, tinting, and lamination.",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "BEAUTY",
    featured: true,
    badge: "Destacado",
    badgeEn: "Featured",
  },
  {
    code: "SVC_044",
    slug: "limpieza-facial-express",
    category: "facial",
    name: "🧴 Limpieza Facial Express",
    nameEn: "🧴 Express Facial Cleanse",
    duration: 30,
    price: 48,
    includes: "Limpieza rápida pero efectiva para remover impurezas",
    includesEn: "Quick yet effective cleanse to remove impurities",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_045",
    slug: "facial-glow-premium-solo",
    category: "facial",
    name: "✨ Facial Glow Premium",
    nameEn: "✨ Premium Glow Facial",
    duration: 50,
    price: 110,
    includes: "Limpieza + exfoliación + mascarilla de colágeno + luz LED",
    includesEn: "Cleanse + exfoliation + collagen mask + LED light therapy",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_046",
    slug: "facial-mascarilla-lifting",
    category: "facial",
    name: "🌿 Facial con Mascarilla Lifting",
    nameEn: "🌿 Lifting Mask Facial",
    duration: 30,
    price: 65,
    includes: "Mascarilla reafirmante para pieles apagadas con pérdida de firmeza",
    includesEn: "Firming mask for dull skin that has lost elasticity",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_047",
    slug: "facial-mascarilla-barro",
    category: "facial",
    name: "🌋 Limpieza Facial con Mascarilla de Barro",
    nameEn: "🌋 Mud Mask Facial Cleanse",
    duration: 30,
    price: 48,
    includes: "Purifica profundamente gracias a las propiedades detoxificantes del barro",
    includesEn: "Deep purification thanks to mud's detoxifying properties",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
];

export const featuredServices = services.filter((service) => service.featured);

export const servicesByCategory = {
  individual: services.filter((service) => service.category === "individual"),
  couples: services.filter((service) => service.category === "couples"),
  home: services.filter((service) => service.category === "home"),
  program: services.filter((service) => service.category === "program"),
  beauty: services.filter((service) => service.category === "beauty"),
  facial: services.filter((service) => service.category === "facial"),
};
