export type ServiceCategory = "individual" | "couples" | "home" | "program" | "beauty" | "facial";

export type Service = {
  code: string;
  slug: string;
  category: ServiceCategory;
  name: string;
  duration: number;
  price: number;
  includes: string;
  venue: string;
  mode: "IN_BRANCH" | "HOME";
  group: "PROMOS_1P" | "PACK_2P" | "HOME" | "SESSIONS" | "BEAUTY" | "FACIAL";
  featured: boolean;
  badge: string;
  featuredSummary?: string;
};

export const services: Service[] = [
  {
    code: "SVC_016",
    slug: "relax-vital",
    category: "individual",
    name: "🌿 Relax Vital",
    duration: 60,
    price: 70,
    includes: "Masaje Relajante + Reflexología",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: true,
    badge: "Más elegido",
    featuredSummary: "Masaje Relajante + Reflexología",
  },
  {
    code: "SVC_012",
    slug: "espalda-libre",
    category: "individual",
    name: "🌤️ Espalda Libre",
    duration: 45,
    price: 58,
    includes: "Masaje Relajante o Descontracturante de Parte Superior",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_013",
    slug: "alivio-integral",
    category: "individual",
    name: "💆‍♂️ Alivio Integral",
    duration: 60,
    price: 80,
    includes: "Masaje Descontracturante + Reflexología",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: true,
    badge: "Ideal para tensiones",
    featuredSummary: "Masaje Descontracturante + Reflexología",
  },
  {
    code: "SVC_019",
    slug: "terapia-vita",
    category: "individual",
    name: "👐 Terapia Vita",
    duration: 60,
    price: 80,
    includes: "Masaje Terapéutico ideal para aliviar tensiones musculares",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_017",
    slug: "balance-plus",
    category: "individual",
    name: "🌿 Balance Plus",
    duration: 70,
    price: 88,
    includes: "Masaje Relajante o Descontracturante + Piedras Calientes + Reflexología + Exfoliación de Espalda",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: true,
    badge: "Experiencia completa",
    featuredSummary: "Masaje Relajante o Descontracturante + Piedras Calientes + Reflexología + Exfoliación de Espalda",
  },
  {
    code: "SVC_007",
    slug: "glow-facial",
    category: "individual",
    name: "✨ Glow Facial",
    duration: 75,
    price: 99,
    includes: "Masaje Relajante o Descontracturante + Limpieza Facial Express con Mascarilla de Colágeno",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_018",
    slug: "deep-balance-120",
    category: "individual",
    name: "🌙 Deep Balance 120",
    duration: 120,
    price: 148,
    includes: "Masaje Relajante y Descontracturante + Piedras Calientes + Reflexología + Compresas Calientes",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_011",
    slug: "aroma-zen",
    category: "individual",
    name: "🕯️ Aroma Zen",
    duration: 60,
    price: 89,
    includes: "Masaje Relajante o Descontracturante + Reflexología + Aromaterapia",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_020",
    slug: "coco-premium",
    category: "individual",
    name: "🥥 Coco Premium",
    duration: 80,
    price: 100,
    includes: "Masaje Relajante o Descontracturante + Piedras Calientes + Exfoliación de Coco + Reflexología + Aromaterapia + 1 Copa de Vino o Infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_030",
    slug: "piedras-calientes",
    category: "individual",
    name: "🔥 Piedras Calientes",
    duration: 60,
    price: 75,
    includes: "Masaje relajante con piedras calientes",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_031",
    slug: "bambuterapia",
    category: "individual",
    name: "🎋 Bambuterapia",
    duration: 60,
    price: 75,
    includes: "Masaje relajante con bambuterapia",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_032",
    slug: "shiatsu",
    category: "individual",
    name: "🙌 Shiatsu",
    duration: 60,
    price: 80,
    includes: "Masaje shiatsu de presión con dedos y palmas para liberar tensión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_033",
    slug: "drenaje-linfatico",
    category: "individual",
    name: "💧 Drenaje Linfático",
    duration: 60,
    price: 70,
    includes: "Masaje de drenaje linfático para reducir retención de líquidos",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_034",
    slug: "masaje-prenatal",
    category: "individual",
    name: "🤰 Masaje Prenatal",
    duration: 60,
    price: 70,
    includes: "Masaje suave y seguro para gestantes. 2 sesiones por S/ 128",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_035",
    slug: "bioenergetico-esferas-solo",
    category: "individual",
    name: "🧿 Bioenergético con Esferas Chinas",
    duration: 70,
    price: 88,
    includes: "Masaje bioenergético con esferas chinas",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_036",
    slug: "ventosas",
    category: "individual",
    name: "🫙 Ventosas + Masaje",
    duration: 60,
    price: 80,
    includes: "Masaje relajante o descontracturante con ventosas",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_037",
    slug: "reflexologia",
    category: "individual",
    name: "🦶 Reflexología",
    duration: 30,
    price: 40,
    includes: "Reflexología podal",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_038",
    slug: "reflexologia-plus",
    category: "individual",
    name: "🦶 Reflexología Plus",
    duration: 45,
    price: 50,
    includes: "Reflexología podal extendida",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_039",
    slug: "para-regalar-60",
    category: "individual",
    name: "🎁 Para Regalar",
    duration: 60,
    price: 98,
    includes: "Masaje relajante + piedras calientes + reflexología + oso de peluche + bebida",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_040",
    slug: "para-regalar-80",
    category: "individual",
    name: "🎁 Para Regalar Plus",
    duration: 80,
    price: 118,
    includes: "Masaje relajante + piedras calientes + reflexología + exfoliación de espalda + oso de peluche + bebida",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_041",
    slug: "bioenergetico-oriental",
    category: "individual",
    name: "🌸 Bioenergético Oriental",
    duration: 70,
    price: 88,
    includes: "Esferas chinas + bambuterapia + reflexología + armonización con cuencos",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_042",
    slug: "glow-facial-plus",
    category: "individual",
    name: "✨ Glow Facial Plus",
    duration: 80,
    price: 120,
    includes: "Masaje + piedras calientes + limpieza facial + bebida",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_043",
    slug: "glow-facial-premium",
    category: "individual",
    name: "✨ Glow Facial Premium",
    duration: 90,
    price: 155,
    includes: "Masaje + piedras calientes + mascarilla lifting de ácido hialurónico + serum antioxidante + bebida",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PROMOS_1P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_002",
    slug: "break-time",
    category: "couples",
    name: "⏳ Break Time",
    duration: 50,
    price: 118,
    includes: "Masaje relajante o descontracturante",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_014",
    slug: "sacro-craneal",
    category: "couples",
    name: "🧠 Sacro Craneal",
    duration: 60,
    price: 138,
    includes: "Masaje sacro-craneal + compresa herbal + masaje relajante + reflexología podal + aromaterapia",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_003",
    slug: "respira",
    category: "couples",
    name: "🌬️ Respira",
    duration: 60,
    price: 149,
    includes: "Masaje relajante + bambuterapia + hidratación corporal + reflexología podal + copa de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_010",
    slug: "relax",
    category: "couples",
    name: "✨ Relax",
    duration: 60,
    price: 149,
    includes: "Masaje relajante y/o descontracturante + piedras calientes + reflexología podal + aromaterapia + copa de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: true,
    badge: "Para dos",
    featuredSummary: "Masaje relajante y/o descontracturante + piedras calientes + reflexología podal",
  },
  {
    code: "SVC_004",
    slug: "vita",
    category: "couples",
    name: "🌄 Vita",
    duration: 70,
    price: 159,
    includes: "Masaje relajante + piedras calientes + reflexología podal + aromaterapia + exfoliación posterior (chocolate o durazno) + copa de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_005",
    slug: "renova",
    category: "couples",
    name: "🌶️ Renova",
    duration: 70,
    price: 159,
    includes: "Masaje relajante herbal + bambuterapia + reflexología podal + aromaterapia + masaje bioenergético con esferas chinas + copa de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_006",
    slug: "renace",
    category: "couples",
    name: "🍃 Renace",
    duration: 65,
    price: 169,
    includes: "Masaje descontracturante/relajante + sesión TENS + exfoliación de espalda + bioenergético con esferas chinas + reflexología podal + aromaterapia + 2 copas de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_021",
    slug: "esencia",
    category: "couples",
    name: "🕯️ Esencia",
    duration: 70,
    price: 178,
    includes: "Masaje relajante + piedras calientes + reflexología podal + aromaterapia con vela de soja artesanal + copa de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_001",
    slug: "deluxe",
    category: "couples",
    name: "🌟 Deluxe",
    duration: 90,
    price: 229,
    includes: "Masaje relajante + descontracturante + piedras calientes + reflexología podal + aromaterapia + limpieza facial express con mascarilla de colágeno + copa de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: true,
    badge: "Premium",
    featuredSummary: "Masaje relajante + descontracturante + piedras calientes + reflexología podal",
  },
  {
    code: "SVC_022",
    slug: "royale",
    category: "couples",
    name: "👑 Royale",
    duration: 120,
    price: 279,
    includes: "Masaje relajante/descontracturante (full body) + piedras calientes + exfoliación de espalda + mascarilla de ácido hialurónico + reflexología podal + hidratación de manos + aromaterapia",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_015",
    slug: "supreme",
    category: "couples",
    name: "🌅 Supreme",
    duration: 150,
    price: 329,
    includes: "Masaje relajante/descontracturante (full body) + piedras calientes + exfoliación de espalda + mascarilla de ácido hialurónico + reflexología podal + hidratación corporal + aromaterapia con vela de soja artesanal + descanso en sala de pareja + copa de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: true,
    badge: "Signature",
    featuredSummary: "Masaje relajante/descontracturante (full body) + piedras calientes + exfoliación de espalda",
  },
  {
    code: "SVC_048",
    slug: "facial-express-2p",
    category: "couples",
    name: "💑 Facial Express en Pareja",
    duration: 70,
    price: 219,
    includes: "Masaje + piedras calientes + limpieza facial + mascarilla de colágeno + 2 copas de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_049",
    slug: "facial-full-body-2p",
    category: "couples",
    name: "💑 Facial Full Body en Pareja",
    duration: 90,
    price: 269,
    includes: "Masaje completo + piedras calientes + exfoliación + mascarilla de ácido hialurónico + 2 copas de vino o infusión",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_050",
    slug: "coco-premium-2p",
    category: "couples",
    name: "🥥 Coco Premium en Pareja",
    duration: 80,
    price: 210,
    includes: "Masaje relajante y/o descontracturante + piedras calientes + exfoliación de coco + reflexología podal",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "PACK_2P",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_009",
    slug: "masaje-domicilio-1-hora",
    category: "home",
    name: "Masaje a domicilio (1 hora)",
    duration: 60,
    price: 120,
    includes: "Servicio a domicilio con camilla. Servicios disponibles: masaje relajante, descontracturante, deportivo, terapéutico, holístico o reflexología podal. Traslado incluido a Miraflores. Recargo de S/30 para San Borja, Surco, San Isidro y Barranco. Reserva con mínimo 24 horas de anticipación.",
    venue: "Lima",
    mode: "HOME",
    group: "HOME",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_008",
    slug: "masaje-domicilio-2-horas",
    category: "home",
    name: "Masaje a domicilio (2 horas)",
    duration: 120,
    price: 230,
    includes: "Servicio a domicilio con camilla. Servicios disponibles: masaje relajante, descontracturante, deportivo, terapéutico, holístico o reflexología podal. Traslado incluido a Miraflores. Recargo de S/30 para San Borja, Surco, San Isidro y Barranco. Reserva con mínimo 24 horas de anticipación.",
    venue: "Lima",
    mode: "HOME",
    group: "HOME",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_024",
    slug: "programa-relajante-5-sesiones",
    category: "program",
    name: "Programa Relajante – 5 sesiones",
    duration: 60,
    price: 248,
    includes: "5 sesiones de masaje relajante",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_025",
    slug: "programa-relajante-10-sesiones",
    category: "program",
    name: "Programa Relajante – 10 sesiones",
    duration: 60,
    price: 408,
    includes: "10 sesiones de masaje relajante",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_026",
    slug: "programa-terapia-muscular-5-sesiones",
    category: "program",
    name: "Programa Terapia Muscular – 5 sesiones",
    duration: 60,
    price: 325,
    includes: "5 sesiones: descontracturante, terapéutico, piedras calientes o bambuterapia",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_023",
    slug: "programa-terapia-muscular-10-sesiones",
    category: "program",
    name: "Programa Terapia Muscular – 10 sesiones",
    duration: 60,
    price: 640,
    includes: "10 sesiones: descontracturante, terapéutico, piedras calientes o bambuterapia",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "SESSIONS",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_027",
    slug: "lifting-de-pestanas",
    category: "beauty",
    name: "Lifting de Pestañas",
    duration: 60,
    price: 90,
    includes: "Eleva y realza las pestañas naturales desde la raíz. Incluye tinturado con henna.",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "BEAUTY",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_028",
    slug: "planchado-de-cejas",
    category: "beauty",
    name: "Planchado de Cejas",
    duration: 25,
    price: 50,
    includes: "Alinea y define las cejas, ayudando a controlar el vello rebelde y resaltar su forma natural.",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "BEAUTY",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_029",
    slug: "lifting-tinturado-planchado-cejas",
    category: "beauty",
    name: "Lifting de Pestañas + Tinturado + Planchado de Cejas",
    duration: 90,
    price: 130,
    includes: "Tratamiento integral para realzar pestañas y cejas con lifting, tinturado y planchado.",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "BEAUTY",
    featured: true,
    badge: "Destacado",
  },
  {
    code: "SVC_044",
    slug: "limpieza-facial-express",
    category: "facial",
    name: "🧴 Limpieza Facial Express",
    duration: 30,
    price: 48,
    includes: "Limpieza rápida pero efectiva para remover impurezas",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_045",
    slug: "facial-glow-premium-solo",
    category: "facial",
    name: "✨ Facial Glow Premium",
    duration: 50,
    price: 110,
    includes: "Limpieza + exfoliación + mascarilla de colágeno + luz LED",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_046",
    slug: "facial-mascarilla-lifting",
    category: "facial",
    name: "🌿 Facial con Mascarilla Lifting",
    duration: 30,
    price: 65,
    includes: "Mascarilla reafirmante para pieles apagadas con pérdida de firmeza",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
  {
    code: "SVC_047",
    slug: "facial-mascarilla-barro",
    category: "facial",
    name: "🌋 Limpieza Facial con Mascarilla de Barro",
    duration: 30,
    price: 48,
    includes: "Purifica profundamente gracias a las propiedades detoxificantes del barro",
    venue: "Ambas",
    mode: "IN_BRANCH",
    group: "FACIAL",
    featured: false,
    badge: "",
  },
];

export const featuredServices = services.filter((service) => service.featured);

export const servicesByCategory = {
  individual: services.filter((service) => service.category === "individual"),
  couples: services.filter((service) => service.category === "couples"),
  home: services.filter((service) => service.category === "home"),
  program: services.filter((service) => service.category === "program"),
  beauty: services.filter((service) => service.category === "beauty"),
  facial: services.filter((service) => service.category === "facial"),
};
